// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROGRAMA_BOVINO.persistencia;

namespace PROGRAMA_BOVINO.persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220901225759_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("bovino.dominio.Aper_vaca", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cod_Vaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propietario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Veterinario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Aper_Vacas");
                });

            modelBuilder.Entity("bovino.dominio.Historia_Clinica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Animo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha_Visita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frecuencia_Cardiaca")
                        .HasColumnType("int");

                    b.Property<int>("Frecuencia_Respiratoria")
                        .HasColumnType("int");

                    b.Property<int>("Id_Historia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Vaca")
                        .HasColumnType("int");

                    b.Property<int>("Id_Veterinario")
                        .HasColumnType("int");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Historias_Clinicas");
                });

            modelBuilder.Entity("bovino.dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("bovino.dominio.Aper_propietario", b =>
                {
                    b.HasBaseType("bovino.dominio.Persona");

                    b.Property<int>("Id_Propietario")
                        .HasColumnType("int");

                    b.Property<int>("Nombre_Hacienda")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Aper_propietario");
                });

            modelBuilder.Entity("bovino.dominio.Aper_veterinario", b =>
                {
                    b.HasBaseType("bovino.dominio.Persona");

                    b.Property<int>("Id_Veterinario")
                        .HasColumnType("int");

                    b.Property<int>("Tarjeta_Profesional")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Aper_veterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
